import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App", // here we are using it simply as string
  //  Now we will use it as an object
  title: {
    default: "NextJs App",
    // to prefix and suffix we can use template property
    template: "%s | NextJs App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
        </div>
        {children}
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
