// metadata.ts
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "NextJs App",
    template: "%s | NextJs App",
  },
  description: "Generated by create next app",
};
